# Service definition
name: mod-ServiceWrapper
description: a service to launch another service and get full ServiceRunner support

# No dependencies
dependencies: []

# No outputs (You'll probably want to update this or `dependencies`)
outputs: []

# Runtime options
options: []